### ISSUE TITLE
`TypeError: c.on is not a function`

### ISSUE THREAD

**Issue by hcientist** [sammccord/perge#3]
```
...
import Perge from "perge";
// instantiate library
const perge = new Perge(myId);
// connect to a peer
perge.connect(friendId, {
	options: {
		host: `localhost:${PORT}`,
		key: "peerjs",
	}
});
...
```
I get the error in calling `connect` probably i'm doing it in a very wrong way? More error info follows.
```
TypeError: c.on is not a function
./node_modules/perge/dist/index.m.js/r</c.connect
src/index.ts:68

  65 |   // types
  66 |   ImmutableStateInvariantMiddlewareOptions
  67 | } from './immutableStateInvariantMiddleware'
> 68 | export {
  69 |   // js
  70 |   createSerializableStateInvariantMiddleware,
  71 |   findNonSerializableValue,
```

**Comment by nwself** [comment]
I believe [this is the unminified line](https://github.com/sammccord/perge/blob/master/src/index.ts#L64).

The connect function takes 3 arguments:
```
public connect(
    id: string,
    conn?: Peer.DataConnection,
    options?: Peer.PeerConnectOption
  ): Peer.DataConnection { 
```

Looks like you need to pass a `null` as the `conn` argument if you want to pass `options`:
```
perge.connect(friendId, null, { host: host, key: key })
```

EDIT:

Actually it looks like you are passing [PeerJS constructor options](https://peerjs.com/docs.html#peer) into `perge.connect` which forwards them to `peer.connect`. You can't pass options for PeerJs into the Perge constructor. Instead you should make the peer yourself and pass it in the `config` argument to [the Perge constructor](https://github.com/sammccord/perge/blob/master/src/index.ts#L34).
