### ISSUE TITLE
Query regarding offline synchronization

### ISSUE THREAD

**Issue by lorefnon** [sammccord/perge#4]
Thanks for creating this library. 

Looking at the implementation and skimming through the docs of PeerJS, it would appear that this library will only sync changes between two peers A & B only if A & B are both online at the same time. If either A or B temporarily gets disconnected then any changes to the automerge document (made during this duration) will never get synced eventually. 

Is it correct to assume that for handling scenarios like above it is the application's responsibility to implement a separate pull mechanism ?

**Comment by sammccord** [comment]
Hey, sorry I missed this.
You'd be correct, I consider it the application's responsibility to handle that use case, but if you'd like to propose an API, I'd definitely be open to discussing it further.
